"""Add generic platform tables for Phase 8 generalization

Revision ID: 8bb58781e0b1
Revises: 259e703b8b68
Create Date: 2025-11-05 16:42:25.797109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb58781e0b1'
down_revision: Union[str, Sequence[str], None] = '259e703b8b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=False)
    op.create_index(op.f('ix_sources_source_type'), 'sources', ['source_type'], unique=False)
    op.create_table('scraped_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('scrape_job_id', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scraping_jobs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_data_id'), 'scraped_data', ['id'], unique=False)
    op.create_index(op.f('ix_scraped_data_scraped_at'), 'scraped_data', ['scraped_at'], unique=False)
    op.create_index(op.f('ix_scraped_data_source_id'), 'scraped_data', ['source_id'], unique=False)
    op.create_table('processed_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraped_data_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('key_concepts', sa.JSON(), nullable=True),
    sa.Column('data_metadata', sa.JSON(), nullable=True),
    sa.Column('processor_module', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scraped_data_id'], ['scraped_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_data_id'), 'processed_data', ['id'], unique=False)
    op.create_index(op.f('ix_processed_data_processed_at'), 'processed_data', ['processed_at'], unique=False)
    op.create_index(op.f('ix_processed_data_scraped_data_id'), 'processed_data', ['scraped_data_id'], unique=False)
    op.create_index(op.f('ix_processed_data_title'), 'processed_data', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_data_title'), table_name='processed_data')
    op.drop_index(op.f('ix_processed_data_scraped_data_id'), table_name='processed_data')
    op.drop_index(op.f('ix_processed_data_processed_at'), table_name='processed_data')
    op.drop_index(op.f('ix_processed_data_id'), table_name='processed_data')
    op.drop_table('processed_data')
    op.drop_index(op.f('ix_scraped_data_source_id'), table_name='scraped_data')
    op.drop_index(op.f('ix_scraped_data_scraped_at'), table_name='scraped_data')
    op.drop_index(op.f('ix_scraped_data_id'), table_name='scraped_data')
    op.drop_table('scraped_data')
    op.drop_index(op.f('ix_sources_source_type'), table_name='sources')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
